sudo: required

services:
- docker

before_install:
- docker build -t build_centos_23 docker/centos_23/
- docker build -t build_centos_22 docker/centos_22/

script:
- docker run -v $TRAVIS_BUILD_DIR:/home/sd/ build_centos_23 /bin/sh -c "cd /home/sd/; make clean; make all; make test"
- docker run -v $TRAVIS_BUILD_DIR:/home/sd/ build_centos_22 /bin/sh -c "cd /home/sd/; make clean; make all; make test"
